// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ0-YXlxrsszAul6SzoFnXpe-I_19VehY',
    appId: '1:982274854008:web:0ef3550e06a050c107318d',
    messagingSenderId: '982274854008',
    projectId: 'citycare-5aa31',
    authDomain: 'citycare-5aa31.firebaseapp.com',
    storageBucket: 'citycare-5aa31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIi3SQ5vHhB3fao-SAGYPv9UpRjpKVP-0',
    appId: '1:982274854008:android:69e327a4e75281e707318d',
    messagingSenderId: '982274854008',
    projectId: 'citycare-5aa31',
    storageBucket: 'citycare-5aa31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFoDpbiTaVkl5nEFC3iLpZPt10VR8V_o',
    appId: '1:982274854008:ios:eed1aab57d93cc6807318d',
    messagingSenderId: '982274854008',
    projectId: 'citycare-5aa31',
    storageBucket: 'citycare-5aa31.firebasestorage.app',
    iosBundleId: 'com.example.cityCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMFoDpbiTaVkl5nEFC3iLpZPt10VR8V_o',
    appId: '1:982274854008:ios:eed1aab57d93cc6807318d',
    messagingSenderId: '982274854008',
    projectId: 'citycare-5aa31',
    storageBucket: 'citycare-5aa31.firebasestorage.app',
    iosBundleId: 'com.example.cityCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ0-YXlxrsszAul6SzoFnXpe-I_19VehY',
    appId: '1:982274854008:web:e7d39b9a1cf2cc6007318d',
    messagingSenderId: '982274854008',
    projectId: 'citycare-5aa31',
    authDomain: 'citycare-5aa31.firebaseapp.com',
    storageBucket: 'citycare-5aa31.firebasestorage.app',
  );
}
